### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#566]
This is a somewhat detailed roadmap for the development of this crate as I'd like to be transparent about what changes the user may anticipate. I will update it roughly once a month with all the main milestones.

Right now the current version is `0.22.2`. This plan is not set in store and some other features could be implemented outside of these milestones (e.g. regex config support, or moving some dependencies behind features).

> :heart:  If you'd like to help the development, consider [sponsoring me](https://github.com/sponsors/Stranger6667) (like Sentry does)

## Full JSON Schema support

Missing non-optional test cases:

- [ ] `unevaluatedItems` (WIP)
- [ ] `vocabulary`
- [ ] 1 failing `unevaluatedProperties` that depends on `unevaluatedItems`
- [ ] 1 failing `$ref` that depends on `unevaluatedItems`

Some optional will be resolved along with the ones above, however, some `bignum` tests for Draft 4 depend on parsing numbers with arbitrary precision which I plan to address later.

## Non-blocking resolving

Right now, the resolving of external references happens during the building phase, which makes it relatively straightforward to implement non-blocking resolving (actually, I'd like to retrieve resources in batches rather than sequentially too).

Along with this change, I'd like to expose custom resolvers to Python bindings + hopefully with async too, but not 100% sure about this.

## Better errors

The main issue with errors is that `validate` returns an iterator, but I'd rather have `validate` + `iter_errors` where the former returns `Result<(), ValidationError>`

As the end goal the errors should:

- Support customization of error messages
- Be easily usable without lifetime issues

I'd also think about separating schema & instance errors.

## Output formats

Adopt naming from the "next" draft + implement a hierarchical style. At this point, I want to separate all the annotation storage from the main graph, as it implies overhead for `is_valid` and `validate`.

## Rework Python bindings

- [ ] ABI3 wheels
- [ ] CI cleanup
- [ ] PyPy support
- [ ] Python 3.13 (it could happen earlier too)
- [ ] Output formats

For a long time, I wanted to implement generic JSON input, I'll try to work on it at this stage. In Python bindings, sometimes the overhead data (de)-serialization during building a validator / validation is up to 80%, having generic input will greatly speed up everything.

Arbitrary precision also goes here, I'd like to have it behind a flag, so it could be disabled by default, but enabled in Python bindings.

## WASM

It should "just work", maybe except for filesystem resolving, but network stuff could work via web_sys (I've tried it in `css-inline`). 

- [ ] Run tests on WASM as a part of CI
- [ ] Demo website with WASM

## Performance, performance, performance

I have tons of ideas about it as my main use case is to speed up the generation of instances that match a schema (in `hypothesis-jsonschema` & `schemathesis`), hence I am going to focus on the `is_valid` performance because the exact errors don't matter in this case.

**Comment by jpmckinney** [comment]
> Along with this change, I'd like to expose custom resolvers to Python bindings + hopefully with async too, but not 100% sure about this.

I presently use python-jsonschema, where I use custom resolvers for a few reasons:

1. The default resolver follows file:// URLs. If an application dereferences and renders a user-provided schema, this can be used to read any file on the filesystem to which the web process has access. I therefore use a custom resolver that only resolves HTTP and HTTPS URLs (this is vulnerable to server-side request forgery, but I'm less worried about that).
2. I work with JSON Schema where users are allowed to "patch" the default schema, using JSON Merge Patch (RFC 7386). I use python-jsonschema's [registry](https://referencing.readthedocs.io/en/stable/api/#referencing.Registry) to make references to the default schema resolve to the patched schema.

It would be really nice to be able to control (1).

For (2), would a workaround be to provide only dereferenced schema to jsonschema_rs?

**Comment by Stranger6667** [comment]
Hey @jpmckinney

Thank you for bringing this up! 

1. Good to know this exact use case, I think that exposing resolvers should not be an issue and could be implemented similarly to how custom format validators work right now.
2. I am not 100% sure about a workaround (if you could provide an example, it would help), however, as this project practically followed the same registry-based design for references, I think we can expose the same functionality to Python bindings and it should be enough for your use case. It also seems like the feature is quite related to #432 & #452

**Comment by Stranger6667** [comment]
@jpmckinney I realized now that both things you mention are available in Python bindings. Custom [retrievers](https://github.com/Stranger6667/jsonschema/tree/master/crates/jsonschema-py#external-references) AND [registries](https://github.com/Stranger6667/jsonschema/tree/master/crates/jsonschema-py#external-references) (they can use retrievers too). Hopefully, it could help in your use case, the API is somewhat similar to Python's `jsonschema`

**Comment by Stranger6667** [comment]
Most of the milestones in this roadmap are already done and there is a separate issue for Generic JSON #239. Closing it to have a cleaner set of opened issues.
